name: Promote Dev to Prod

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: my-site

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image variables
        run: |
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_BASE=${{ env.REGISTRY }}/$OWNER_LOWER/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Retag Dev as Prod
        run: |
          docker buildx imagetools create \
            -t ${{ env.IMAGE_BASE }}:prod \
            ${{ env.IMAGE_BASE }}:dev